<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MackySoft.Navigathena" Version="$(NavigathenaPackageVersion)" />
    <PackageReference Include="MackySoft.Navigathena.MicrosoftDI" Version="$(NavigathenaPackageVersion)" />
  </ItemGroup>
</Project>
