blank_issues_enabled: false
contact_links:
    - name: Usage examples
      url: https://github.com/mackysoft/Navigathena/tree/main/tests/Unity/Assets/Samples
      about: Unity setup and examples with and without dependency injection.
