<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../eng/UnitySourcePackage.props" />
  <PropertyGroup>
    <Description>Unity UI Toolkit adapters and styles for Navigathena. Source and assets for NuGetForUnity.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MackySoft.Navigathena.Unity/MackySoft.Navigathena.Unity.csproj" />
  </ItemGroup>
</Project>
